services:
  inventorymanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/InventoryManagement.Api.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=inventory-dev-password
    ports:
      - "58995:8080"
      - "7280:8081"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
