// <auto-generated />
using System;
using InventoryManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260623213020_AddArticleActivityStatus")]
    partial class AddArticleActivityStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("InventoryManagement.Domain.Articles.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles", (string)null);

                    b.HasDiscriminator<string>("ArticleType").HasValue("Article");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockBucket.StockBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("StockBuckets", (string)null);

                    b.HasDiscriminator<string>("BucketType").HasValue("StockBucket");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ArticleMovements", (string)null);

                    b.HasDiscriminator<string>("MovementType").HasValue("StockMovement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.StockMovementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StockBucketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StockMovementId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockBucketId");

                    b.HasIndex("StockMovementId");

                    b.ToTable("StockMovementLines", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Domain.Articles.FoodArticle", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.Articles.Article");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Articles.NonFoodArticle", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.Articles.Article");

                    b.HasDiscriminator().HasValue("NonFood");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockBucket.FoodStockBucket", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.StockBucket.StockBucket");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExpirationDate");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockBucket.NonFoodStockBucket", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.StockBucket.StockBucket");

                    b.Property<string>("PackagingLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("PackagingLevel");

                    b.HasDiscriminator().HasValue("NonFood");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.InventoryMovement", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.StockMovement.StockMovement");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("InventoryComment");

                    b.HasDiscriminator().HasValue("Inventory");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.SaleMovement", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.StockMovement.StockMovement");

                    b.Property<string>("SaleMode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Sale");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.SupplyMovement", b =>
                {
                    b.HasBaseType("InventoryManagement.Domain.StockMovement.StockMovement");

                    b.HasDiscriminator().HasValue("Supply");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Articles.Article", b =>
                {
                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Money", "PriceExcludingTax", b1 =>
                        {
                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("PriceExcludingTax");

                            b1.HasKey("ArticleId");

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Ean13Reference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("TEXT")
                                .HasColumnName("Reference");

                            b1.HasKey("ArticleId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("PriceExcludingTax")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockBucket.StockBucket", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.StockBucketReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("StockBucketId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(21)
                                .HasColumnType("TEXT")
                                .HasColumnName("Reference");

                            b1.HasKey("StockBucketId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("StockBuckets");

                            b1.WithOwner()
                                .HasForeignKey("StockBucketId");
                        });

                    b.Navigation("Article");

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.StockMovement", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Articles.Article", "Article")
                        .WithMany("StockMovements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.StockMovementLine", b =>
                {
                    b.HasOne("InventoryManagement.Domain.StockBucket.StockBucket", "StockBucket")
                        .WithMany()
                        .HasForeignKey("StockBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Domain.StockMovement.StockMovement", "StockMovement")
                        .WithMany("Lines")
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Quantity", "QuantityAfter", b1 =>
                        {
                            b1.Property<Guid>("StockMovementLineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityAfter");

                            b1.HasKey("StockMovementLineId");

                            b1.ToTable("StockMovementLines");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementLineId");
                        });

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Quantity", "QuantityBefore", b1 =>
                        {
                            b1.Property<Guid>("StockMovementLineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityBefore");

                            b1.HasKey("StockMovementLineId");

                            b1.ToTable("StockMovementLines");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementLineId");
                        });

                    b.Navigation("QuantityAfter");

                    b.Navigation("QuantityBefore");

                    b.Navigation("StockBucket");

                    b.Navigation("StockMovement");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Articles.FoodArticle", b =>
                {
                    b.OwnsMany("InventoryManagement.Domain.Articles.FoodArticleSaleMode", "_saleModes", b1 =>
                        {
                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("SaleMode");

                            b1.HasKey("ArticleId", "Value");

                            b1.ToTable("FoodArticleSaleModes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("_saleModes");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.SaleMovement", b =>
                {
                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.VatRate", "VatRate", b1 =>
                        {
                            b1.Property<Guid>("SaleMovementId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("VatRate");

                            b1.HasKey("SaleMovementId");

                            b1.ToTable("ArticleMovements");

                            b1.WithOwner()
                                .HasForeignKey("SaleMovementId");
                        });

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Money", "UnitPriceExcludingTax", b1 =>
                        {
                            b1.Property<Guid>("SaleMovementId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceExcludingTax");

                            b1.HasKey("SaleMovementId");

                            b1.ToTable("ArticleMovements");

                            b1.WithOwner()
                                .HasForeignKey("SaleMovementId");
                        });

                    b.OwnsOne("InventoryManagement.Domain.Shared.ValueObjects.Money", "UnitPriceIncludingTax", b1 =>
                        {
                            b1.Property<Guid>("SaleMovementId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceIncludingTax");

                            b1.HasKey("SaleMovementId");

                            b1.ToTable("ArticleMovements");

                            b1.WithOwner()
                                .HasForeignKey("SaleMovementId");
                        });

                    b.Navigation("UnitPriceExcludingTax")
                        .IsRequired();

                    b.Navigation("UnitPriceIncludingTax")
                        .IsRequired();

                    b.Navigation("VatRate")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Domain.Articles.Article", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("InventoryManagement.Domain.StockMovement.StockMovement", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
